---
plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# Style/StringLiterals:
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   EnforcedStyle: double_quotes

