#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gli'
require 'elastic_op'
require 'elastic_op/cli'

class ElasticOpCli
  extend GLI::App

  program_desc 'Elastic Op'
  version ElasticOp::VERSION

  subcommand_option_handling :normal
  arguments :strict

  desc 'Elasticsearch URL'
  flag %i[url U], type: String, default_value: 'https://localhost:9200'

  desc 'Username for basic authentication'
  flag %i[username u], type: String

  desc 'Password for basic authentication'
  flag %i[password p], type: String

  desc 'Logging level (debug, info, warn, error, fatal)'
  flag %i[log-level L log_level], type: String,
                                  default_value: 'info'

  desc 'SSL verify'
  switch %i[ssl-verify ssl_verify], default_value: true

  desc 'CA certificate'
  flag %i[ca], type: String

  desc 'Output format'
  flag %i[format F],
       default_value: :pretty

  desc 'Cluster operations'
  command :cluster do |cluster|
    cluster.desc 'Cluster version'
    cluster.command :version do |cluster_version|
      cluster_version.action do |_global_options, _options, _args|
        @cli.cluster.version
      end
    end

    cluster.desc 'Cluster health'
    cluster.command :health do |cluster_health|
      cluster_health.action do |_global_options, _options, _args|
        @cli.cluster.health
      end
    end
  end

  desc 'Node operations'
  command [:node, :nodes] do |_node|
    true
  end

  desc 'Cat operations'
  command [:cat] do |cat|
    cat.desc 'Cat indices'
    cat.command :indices do |cat_indices|
      cat_indices.action do |_global_options, options, _args|
        @cli.cat.indices(options: options)
      end
    end
  end

  desc 'Index operations'
  command [:indices, :index] do |indices|
    indices.desc 'Indices list'
    indices.command :list do |indices_list|
      indices_list.action do |_global_options, options, args|
        @cli.indices.get(args, options: options)
      end
    end
  end

  desc 'Shard operations'
  command :shard do |shard|
    shard.desc 'Node Shard evacuate'
    shard.arg_name 'shard_pattern', [:multiple]
    shard.command :evacuate do |shard_evacuate|
      shard_evacuate.flag :count, :c,
                          type: Integer,
                          required: true,
                          default_value: 1,
                          desc: 'Count of shards to evacuate.'

      shard_evacuate.flag :order, :o,
                          type: String,
                          must_match: /biggest/i,
                          default_value: 'biggest',
                          desc: 'Order of evacuation.'

      shard_evacuate.flag :source_node, :s,
                          type: String,
                          required: true,
                          desc: 'Specific source node to move shards FROM.'

      shard_evacuate.flag :target_node, :t,
                          type: String,
                          desc: 'Specific target node to move shards TO.'

      shard_evacuate.action do |_global_options, options, args|
        @cli.shard.evacuate(args, options: options)
      end
    end
  end

  desc 'Dangling operations'
  command :dangling do |dangling|
    dangling.desc 'Dangling list'
    dangling.command :list do |danging_list|
      danging_list.action do |_global_options, options, _args|
        @cli.dangling.list(options: options)
      end
    end

    dangling.desc 'Dangling import'
    dangling.arg_name 'index_uuid', [:multiple]
    dangling.command :import do |dangling_import|
      dangling_import.action do |_global_options, options, args|
        @cli.dangling.import(index_uuids: args, options: options)
      end
    end

    dangling.desc 'Dangling delete'
    dangling.arg_name 'index_uuid', [:multiple]
    dangling.command :delete do |dangling_delete|
      dangling_delete.action do |_global_options, options, args|
        @cli.dangling.delete(index_uuids: args, options: options)
      end
    end

    dangling.desc 'Dangling delete all'
    dangling.command :'delete-all' do |dangling_delete_all|
      dangling_delete_all.action do |_global_options, options, _args|
        @cli.dangling.delete_all(options: options)
      end
    end
  end

  pre do |global, _command, _options, _args|
    @cli = ElasticOp::Cli.new(options: global)

    true
  end

  post do |_global, _command, _options, _args|
    true
  end

  on_error do |exception|
    if ENV['DEBUG']
      warn "❌ Error: #{exception.message}"
      warn "  Exception: #{exception.class}"
      warn '  Backtrace:'
      # exception.backtrace.first(10).each do |line|
      exception.backtrace.each do |line|
        warn "    #{line}"
      end
    end

    true
  end
end

exit ElasticOpCli.run(ARGV)
